// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';


// 1. Import AuthProvider (แก้ Path ให้ถูกตามที่คุณวางไฟล์)
import { AuthProvider } from "./context/AuthContext"; 

// import { CartProvider } from "./CartContext"; // (เดาว่าคุณน่าจะมี CartProvider ด้วย)

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BreadShop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 2. เอา AuthProvider มาครอบเนื้อหาทั้งหมดตรงนี้ */}
        <AuthProvider>
           <Toaster position="top-right"  reverseOrder={false} />
            {/* <CartProvider>  <-- ถ้ามี CartProvider ก็ซ้อนกันแบบนี้ */}
              {children}
            {/* </CartProvider> */}
        </AuthProvider>
      </body>
    </html>
  );
}
